name: daily_money
description: "A new Flutter project."


publish_to: 'none' 













version: 1.0.0+1

environment:
  sdk: ^3.10.4







dependencies:
  flutter:
    sdk: flutter

  
  
  cupertino_icons: ^1.0.8
  get: ^4.7.3
  google_fonts: ^6.3.3
  supabase: ^2.10.2
  supabase_flutter: ^2.12.0
  flutter_dotenv: ^6.0.0
  easy_date_timeline: ^2.0.9
  intl: ^0.20.2
  fl_chart: ^1.1.1
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  
  
  
  
  
  flutter_lints: ^6.0.0

flutter:
  assets:
    - assets/icons/
    - .env

  
  
  
  uses-material-design: true

  
  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
